comment:
  layout: 'files'
  behavior: 'default'

flags:
  admin:
    paths:
      - /packages/admin/**/*
    carryforward: false
  everything-else:
    paths:
      - /packages/!(admin)/**/* 
    carryforward: false