version: '2'
services:
  web:
    build:
      context: .
    ports:
      - '80:3000'
      - '88:8888'
      - '443:4443'
      - '7003:7003'
      - '8226:8226'
      - '8228:8228'
      - '43300:43300'
    command: ./scripts/start.sh
    depends_on:
      - postgres
    environment:
      DATABASE_URL: 'postgres://mco@postgres/mco'
      POSTGRES_DB: mco
      POSTGRES_HOST: postgres
      POSTGRES_USER: mco
  postgres:
    image: 'postgres:10'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: mco
      POSTGRES_DB: mco
