version: "2"

services:
  web:
    build: 
      context: .
    ports:
      - "80:80"
      - "443:443"
      - "7003:7003"
      - "8226:8226"
      - "8228:8228"
      - "43300:43300"
    command: "npm start"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://mco@postgres/mco
  postgres:
    image: postgres:10
    environment:
      POSTGRES_USER: mco
      POSTGRES_DB: mco    